recipes:                                       # Configs are parsed and every list is appended to each other, chef handles order and de-duplication
    global:                                    # Recipes mentioned under "global" are installed for all operating systems (we used to support linux, and may do so in the future)
        #- applications::create_var_chef_cache
    mac_os_x:                                  # Recipes mentioned under "mac_os_x" are installed on OSX and OSX Server
        #- homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        #- osxdefaults::dock_automatically_hide_and_show_the_dock
        #- osxdefaults::dock_minimize_to_application
        #- osxdefaults::dock_remove_the_auto-hiding_dock_delay
        #- osxdefaults::menu_show_clock_with_date
#        - nodejs::default                      # Installs nodejs and installs all nodejs packages mentioned in the nodejs:apps attribute
attributes:
    homebrewalt:
        apps:
#            - git
        cask_apps:
            #- google-chrome
            #- firefox
            #- dropbox
            #- onepassword
#    nodejs:
#        apps:
#            - bower
