recipes:
    global:
        #- dotfiles::bash_it
        #- dotfiles::inputrc
        #- dotfiles::gitconfig
        - dotfiles::vim
        #- applications::postgresql
        #- applications::mysql
        #- applications::bash
    mac_os_x:
        - applications::sublime_text_3
        #- nodejs::default
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_unhide_home
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
attributes:
    #mysql_root_password: "password"
    dotfiles:
        vimusers:
            - rs
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
            - sqlite3
            - openssl
            - libtool
            - libxslt
            - libksba
            - libyaml
            - zsh
            - mysql
            - htop
            #- python
            #    --with-brewed-openssl"
        cask_apps:
            - webstorm
            - rubymine
            - pycharm
            - sequel-pro
            - sourcetree
            - recordit
            - alfred
            - dash
            - iterm2
            #- sublime test 3
    git:
        name: sundeer
        email: sundeer@rhsjmm.com
    #nodejs:
    #    apps:
    #        - phonegap
    #        - cordova
    #        - ionic
    #        - bower
    #        - grunt
    #        - grunt-cli




