recipes:
    global:
        - dotfiles::bash_it
        - dotfiles::inputrc
        - dotfiles::gitconfig
        - dotfiles::vim
        - applications::bash
    mac_os_x:
        - applications::sublime_text_3
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_unhide_home
attributes:
    dotfiles:
        vimusers:
            - rs
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
    git:
        name: sundeer
        email: sundeer@rhsjmm.com
    homebrewalt:
        apps:
            - bash-completion
            - git
            - git-extras
            - wget
            - rbenv
            - zsh
        cask_apps:
            - webstorm
            - rubymine
            - pycharm
            - sequel-pro
            - sourcetree
            - recordit

